dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:

  matrix:
    - ARCH_TAG="amd64"   SERVICE="orthanc"
    - ARCH_TAG="amd64"   SERVICE="diana-worker"
    - ARCH_TAG="amd64"   SERVICE="tf-keras"
    - ARCH_TAG="amd64"   SERVICE="tf-keras-sshd"
    - ARCH_TAG="amd64"   SERVICE="movidius"
    - ARCH_TAG="amd64"   SERVICE="movidius-sshd"

# Cross-compile, but never finishes in 50 mins on Travis
#    - ARCH_TAG="arm32v7" SERVICE="orthanc"
#    - ARCH_TAG="arm32v7" SERVICE="diana-worker"
#    - ARCH_TAG="arm32v7" SERVICE="tf-keras"
#    - ARCH_TAG="arm32v7" SERVICE="movidius"

# Build natively on Packet ARM
#    - ARCH_TAG="arm64v8" SERVICE="orthanc"
#    - ARCH_TAG="arm64v8" SERVICE="diana-worker"


before_install:

  # Put docker into "experimental" for manifest function
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' > "$HOME/.docker/config.json"

  # Register qemu as cross-compiler (nothing is fast enough to finish in 50 mins though)
  # TODO: confirm irrelevant and remove
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

  - docker-compose -f docker/docker-compose.builder.yml build $SERVICE-$ARCH_TAG

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # TODO: confirm irrelevant and remove
  - docker push "$DOCKER_USERNAME/$SERVICE:$ARCH_TAG"

  - python3 manifest-it.py rcd-manifests.yml

script: true

after_script: true

# Manifest and push, need a "finally"
