dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  matrix:
    - ARCH_TAG="amd64" RESIN_ARCH="intel-nuc" TINI_BIN="tini"
    - ARCH_TAG="armv7l" RESIN_ARCH="raspberrypi3" TINI_BIN="tini-armhf"

before_install:

  # Put docker into "experimental" for manifest function
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' > "$HOME/.docker/config.json"

  - docker build -t "$DOCKER_USERNAME/diana-worker:$ARCH_TAG" --build-arg "RESIN_ARCH=$RESIN_ARCH" --build-arg "TINI_BIN=$TINI_BIN" docker/diana-worker

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME/diana-worker:$ARCH_TAG"


script: true

after_script: true

  # Manifest and push


