version: '3'

# enable local mode
# $ DOCKER_API_VERSION=1.22 DOCKER_HOST=tcp://resin.local:2375 docker-compose up
# - https://github.com/resin-io-playground/resinos-compose

services:

  broker:
    image: redis
    command: redis-server --requirepass passw0rd!
    ports:
      - "16379:16379"
    environment:
      TZ: America/New_York

  dicom:
    image: derekmerck/orthanc
    ports:
      - "14242:4242"
      - "18042:8042"

  diana-worker:
    image: derekmerck/diana-worker
    links:
      - broker
      - dicom
    environment:
      DIANA_BROKER: redis://:passw0rd!@broker:6379/1
      DIANA_RESULT: redis://:passw0rd!@broker:6379/2

  learn:
    image: derekmerck/tf-keras

  learn-movidius:
    image: derekmerck/movidius
    network_mode: host
    privileged: true
    volumes:
      - "/dev:/dev"
