version: '3'

# amd64 can be compiled and pushed from Travis
# arm32v7 has to cross-compiled currently
# arm64v8 orthanc and diana-worker can be compiled and pushed from Packet

# Resin using Packet ARM servers to compile arm32:
# - https://resin.io/blog/docker-builds-on-arm-servers-youre-not-crazy-your-builds-really-are-5x-faster/
# But apparently cannot cross-compile for rpi natively on a Cavium ThunderX ARMv8:
# - https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2544

services:

# ---------------------------
  # sshd
  # ---------------------------

  sshd-amd64:
    build:
      context: ./sshd
    image: derekmerck/sshd:amd64

  sshd-arm32v7:
    build:
      context: ./sshd
      args:
        RESIN_ARCH: raspberrypi3
    image: derekmerck/sshd:arm32v7

  # ---------------------------
  # orthanc
  # ---------------------------

  orthanc-amd64:
    build:
      context: ./orthanc
    image: derekmerck/orthanc:amd64

  orthanc-arm32v7:
    build:
      context: ./orthanc
      args:
        RESIN_ARCH: raspberrypi3
    image: derekmerck/orthanc:arm32v7

  orthanc-arm64v8:
    build:
      context: ./orthanc
      args:
        RESIN_ARCH: generic-aarch64
    image: derekmerck/orthanc:arm64v8


  # ---------------------------
  # diana-worker
  # ---------------------------

  diana-worker-amd64:
    build:
      context: ./diana-worker
    image: derekmerck/diana-worker:amd64

  diana-worker-arm32v7:
    build:
      context: ./diana-worker
      args:
        RESIN_ARCH: raspberrypi3
    image: derekmerck/diana-worker:arm32v7

  diana-worker-arm64v8:
    build:
      context: ./diana-worker
      args:
        RESIN_ARCH: generic-aarch64
    image: derekmerck/diana-worker:arm64v8


  # ---------------------------
  # tf-keras
  # ---------------------------

  tf-keras-amd64:
    build:
      context: ./tf-keras
    image: derekmerck/tf-keras:amd64

  diana-learn-amd64:
    build:
      context: ./tf-keras
      dockerfile: Dockerfile-worker
    image: derekmerck/diana-learn:amd64

  tf-keras-arm32v7:
    build:
      context: ./tf-keras
      args:
        RESIN_ARCH: raspberrypi3
        TF_WHL_URL: http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/lastSuccessfulBuild/artifact/output-artifacts/
        TF_WHL_FILE: tensorflow-1.9.0rc0-cp34-none-linux_armv7l.whl
    image: derekmerck/tf-keras:arm32v7

  # No TF wheel for aarch64

  tf-keras-sshd-amd64:
    build:
      context: ./tf-keras
      dockerfile: Dockerfile-sshd
    image: derekmerck/tf-keras-sshd:amd64
    depends_on:
      - tf-keras-amd64

  tf-keras-sshd-arm32v7:
    build:
      context: ./tf-keras
      dockerfile: Dockerfile-sshd
      args:
        ARCH_TAG: arm32v7
    image: derekmerck/tf-keras-sshd:arm32v7
      - tf-keras-arm32v7

  # ---------------------------
  # movidius
  # ---------------------------

  movidius-amd64:
    build:
      context: ./movidius
    image: derekmerck/movidius:amd64

  movidius-arm32v7:
    build:
      context: ./movidius
      args:
        RESIN_ARCH: raspberrypi3
    image: derekmerck/movidius:arm32v7

  movidius-sshd-amd64:
    build:
      context: ./movidius
      dockerfile: Dockerfile-sshd
    image: derekmerck/movidius-sshd:amd64
    depends_on:
      - movidius-amd64

  movidius-sshd-arm32v7:
    build:
      context: ./movidius
      dockerfile: Dockerfile-sshd
      args:
        ARCH_TAG: arm32v7
    image: derekmerck/movidius-sshd:arm32v7
    depends_on:
      - movidius-arm32v7
