version: '3'

services:

  # ---------------------------
  # orthanc
  # ---------------------------

  orthanc-arm32v7:
    build:
      context: ./orthanc
      args:
        RESIN_ARCH: raspberrypi3
        TINI_BIN: tini-armhf
    image: derekmerck/orthanc:arm32v7

  orthanc-amd64:
    build:
      context: ./orthanc
    image: derekmerck/orthanc:amd64

  # ---------------------------
  # diana-worker
  # ---------------------------

  diana-worker-arm32v7:
    build:
      context: ./diana-worker
      args:
        RESIN_ARCH: raspberrypi3
        TINI_BIN: tini-armhf
    image: derekmerck/diana-worker:arm32v7

  diana-worker-amd64:
    build:
      context: ./diana-worker
    image: derekmerck/diana-worker:amd64

  # ---------------------------
  # tf-keras
  # ---------------------------

  tf-keras-arm32v7:
    build:
      context: ./learn
      args:
        RESIN_ARCH: raspberrypi3
        TINI_BIN: tini-armhf
        TF_WHL_URL: http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/lastSuccessfulBuild/artifact/output-artifacts/
        TF_WHL_FILE: tensorflow-1.9.0rc0-cp34-none-linux_armv7l.whl
    image: derekmerck/tf-keras:arm32v7

  tf-keras-amd64:
    build:
      context: ./learn
    image: derekmerck/tf-keras:amd64

  # ---------------------------
  # movidius
  # ---------------------------

  movidius-arm32v7:
    build:
      context: ./movidius
      args:
        RESIN_ARCH: raspberrypi3
        TINI_BIN: tini-armhf
    image: derekmerck/movidius:arm32v7

  movidius-amd64:
    build:
      context: ./movidius
    image: derekmerck/movidius:amd64

