ARG ARCH_TAG="amd64"

FROM derekmerck/learn:$ARCH_TAG

RUN apt install -y --no-install-recommends \
         sed \
         build-essential \
         sudo \
         tar \
         udev \
         wget \
         python3-numpy-dev \
    && pip3 install -U pip && pip2 install -U pip \
    && git clone -b ncsdk2 https://github.com/movidius/ncsdk /ncsdk2 \
    && sed -i 's/exit 1//g' /ncsdk2/install.sh

WORKDIR /ncsdk2

RUN make && make install
