---

# Respects ENVs:
# - DIANA_BROKER, DIANA_RESULT

- name: Add system reqs
  package:
    name:
      - git
      - python3
      - python3-numpy
      - python3-dev
      - python3-dbus
      - python3-setuptools
      - python3-pip
      - build-essential
      - libjpeg-dev
      - zlib1g-dev
      - libtiff5-dev

- shell: pip3 install -U pip
  become: yes

- name: Create diana user
  user:
    name: diana
    group: root
    state: present
    home: /home/diana

- git:
    repo: 'https://github.com/derekmerck/diana_plus'
    dest: /home/diana/source

- pip:
    executable: pip3
    name:
      - /opt/diana/packages/diana
      - /opt/diana/packages/guid-mint
    editable: yes
    become: yes
