---

# Should respects ENVs:
# - BROKER_HOST, BROKER_PW

- name: Add system reqs
  package:
    name:
      - git
      - python3
      - python3-numpy
      - python3-dev
      - python3-dbus
      - python3-setuptools
      - python3-pip
      - build-essential
      - libjpeg-dev
      - zlib1g-dev
      - libtiff5-dev

- shell: pip3 install -U pip
  become: yes

- name: Create diana user
  user:
    name: diana
#    uid: 1000
    group: root
    state: present
    home: /opt/diana

- git:
    repo: 'https://github.com/derekmerck/diana-star'
    dest: /opt/diana

- pip:
    executable: pip3
    name:
      - /opt/diana/packages/diana
      - /opt/diana/packages/guid-mint
    editable: yes
